### ISSUE TITLE
Bug in installer and cant install Enso os

### ISSUE THREAD

**Issue by filipeGamaBR** [nick92/Enso-OS#11]

**Comment by filipeGamaBR** [comment]
Well i  cant install  the enso os im my notbook  since the  enso 0.1 i cant, i try rosawriter,rufus,etcher,and unetbootin and after  the installation goes into computer repair mode im teste in uefi mode only ,thanks .

i love your ideas and desing that you have when developing the enso os , i love  styles like macos/macosx 

My hardware:
Dell inspiron 14 5458
Ram:4GBDdr3
intel core i3 5°gen

**Comment by nick92** [comment]
Hey Filipe, 

Sorry about the late reply, is this still an issue for you? 

Unfortunately I don't own this laptop so can't offer much help in terms of installation issues, I've had a quick search around the web and can't see anyone mentioning issues when installing Ubuntu onto this device, and it looks as though it is fully supported from the Ubuntu website. 

Some useful information can be found in these places regarding installing Ubuntu onto UEFI so hopefully they can offer you better help:

[How to Install Ubuntu and Windows Vista or 7 as a Dual Boot on your Dell PC](https://www.dell.com/support/article/uk/en/ukbsdt1/sln151792/how-to-install-ubuntu-and-windows-vista-or-7-as-a-dual-boot-on-your-dell-pc?lang=en)  

[How to install ubuntu in UEFI mode](https://askubuntu.com/questions/927924/how-to-install-ubuntu-in-uefi-mode#928101)

Let me know if these are any help to you

**Comment by lynxmedeiros** [comment]
You can try this tip.
Format the drive in GPT, you can use the Gparted.
I hope it helps.
