### ISSUE TITLE
How to install "Panther Launcher" on Xubuntu

### ISSUE THREAD

**Issue by rafael-neri** [nick92/Enso-OS#12]
How can I download deb packages?

**Comment by nick92** [comment]
You can install it via PPA from our repository with the following commands: 

sudo add-apt-repository ppa:enso-os/stable
sudo apt update && sudo apt install panther-launcher 

Or if you do want the deb package you can download it from:
https://launchpad.net/~enso-os/+archive/ubuntu/stable/+build/13361376/+files/panther-launcher_1.0.23_amd64.deb

**Comment by rafael-neri** [comment]
@nick92 thank you!
