### ISSUE TITLE
Screen Resolution Issue

### ISSUE THREAD

**Issue by adi1090x** [nick92/Enso-OS#15]
![180206130215](https://user-images.githubusercontent.com/26059688/35847228-b4a8b158-0b3f-11e8-9177-382aaa17a790.png)
Hi,... you did good work on it...
i'm facing some issues... i am not able to see the background & i guess it's a resolution issue.
when the display manager starts, i get an black background and the elements ( avator and password box) at center bottom of the screen and clock is also not visible...
can you help me..!
screenshot: this is what appears when i execute /usr/bin/pantheon-greeter.

**Comment by nick92** [comment]
Hey

the background image should automatically be picked up by lightdm, but failing this will load an image from a config  setting in the greeter config file from /etc/lighdm/greeter.conf default-wallpaper.

the clock is hidden is the resolution of the screen is under 1600 - 900, and it looks as though the size of the image is too small to display this. This is something I am looking at fixing in the future and making work on smaller machines. 

Apologies about the late response but hope this helps and have you made any progress?
