### ISSUE TITLE
Some feedback on Enso OS

### ISSUE THREAD

**Issue by gabrc52** [nick92/Enso-OS#17]
I've booted up Enso OS, and here's some feedback I have:

- I really like that XFCE is being used, but there's focus on making it better.

- I really like how the elementary multitasking view was implemented, it's one of the best ones I've used.

- I feel that this distro has lots of potential.

Here are some things that could be improved:

- [x] The default font is set to Source Sans Pro, but it's unavailable, so it falls back to DejaVu Sans or a similar font.

- [x] For some reason, I changed my keyboard layout, but the changes did not apply. (I deleted the English layouts and added a different one, apparently first you have to move the new layout to the top and then delete the default layouts).

- [x] When hovering over a window in the multitasking view, a checkmark appears. This may confuse some users as an "X" is typically used. And, I'd prefer if the number of workspaces wasn't fixed, that option would be nice.

- [x] Not all shortcuts work, for example: Even though it's set in the settings, the Shift+PrtScr shortcut does not seem to work. PrtScr and Alt+PrtScr do work though.

- [ ] Inconsistent scrolling direction when reversing it, for example, it's reversed on Firefox but not on the terminal (Sakura)

- [x] Logging in to XFCE session instead of Xubuntu session breaks the panel configuration, and XFCE panel switch does not include the default Enso configuration to restore it.

- [x] The Application Launcher isn't as lightweight as it could be, and searching for files would be appreciated (I think this is being worked on).

- [ ] Some scaled or dark on dark icons: when adjusting the volume and brightness, Clipman applet (at first I didn't even realize it was there)

- [x] "Window manager" and "Window manager tweaks" under Settings don't open. (Probably due to the elementary wm)

- [x] Add a Show Desktop shortcut

**Comment by nick92** [comment]
Thanks for the feedback! Will work through theme and get them into the Roadmap for 03.

**Comment by nick92** [comment]
Going to close this as all items have either been added to release or are in a project
