### ISSUE TITLE
Can't compile greeter on Debian

### ISSUE THREAD

**Issue by rlue** [nick92/Enso-OS#18]
Trying to build the Pantheon greeter on a fresh install of Debian Stretch. One snag is that there's no `liblightdm-gobject-1-dev` package in the Debian repos — the closest one being `liblightdm-gobject-dev`. I installed that instead, and the build borked with the following output:

```sh
rlue@herringbone:~/Enso-OS/greeter/build$ cmake -DCMAKE_INSTALL_PREFIX=/usr .. && make
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29")
-- Checking for modules 'gee-0.8;liblightdm-gobject-1>=1.2.1;gdk-x11-3.0;clutter-gtk-1.0;gdk-pixbuf-2.0;gl'
--   Found gee-0.8, version 0.18.1
--   Found liblightdm-gobject-1, version 1.18.3
--   Found gdk-x11-3.0, version 3.22.11
--   Found clutter-gtk-1.0, version 1.8.2
--   Found gdk-pixbuf-2.0, version 2.36.5
--   Found gl, version 13.0.6
-- Found Vala: /usr/bin/valac
-- checking for a minimum Vala version of 0.26.0
--   found Vala, version 0.34.7
-- GSettings schemas will be installed locally.
-- GSettings shemas will be compiled.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rlue/Enso-OS/greeter/build
[  3%] Generating data/css.gresource.c
[  7%] Generating src/PantheonGreeter.c, src/SettingsDaemon.c, src/UserList.c, src/UserListActor.c, src/Gateways/DummyGateway.c, src/Gateways/LightDMGateway.c, src/Gateways/LoginGateway.c, src/Interfaces/Credentials.c, src/Interfaces/LoginMask.c, src/LoginOptions/GuestLogin.c, src/LoginOptions/LoginOption.c, src/LoginOptions/ManualLogin.c, src/LoginOptions/UserLogin.c, src/Widgets/CredentialsArea.c, src/Widgets/DeepinBlurEffect.c, src/Widgets/FingerprintCredentials.c, src/Widgets/LoginBox.c, src/Widgets/LoginButtonCredentials.c, src/Widgets/PasswordCredentials.c, src/Widgets/TimeLabel.c, src/Widgets/PowerLabel.c, src/Widgets/Wallpaper.c, src/Widgets/Avatar.c, build/src/config.c
error: Package `liblightdm-gobject-1' not found in specified Vala API directories or GObject-Introspection GIR directories
Compilation failed: 1 error(s), 0 warning(s)
CMakeFiles/pantheon-greeter.dir/build.make:85: recipe for target 'src/PantheonGreeter.c' failed
make[2]: *** [src/PantheonGreeter.c] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pantheon-greeter.dir/all' failed
make[1]: *** [CMakeFiles/pantheon-greeter.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by nick92** [comment]
Try changing the dependency reference in the cmake file and see if that works, there will only need to be 2 changes, and will look like this:

pkg_check_modules (DEPS REQUIRED gee-0.8 liblightdm-gobject gdk-x11-3.0 clutter-gtk-1.0 gdk-pixbuf-2.0 gl) 

PACKAGES
    gee-0.8
    liblightdm-gobject
    posix
    gdk-pixbuf-2.0
    gdk-x11-3.0
    x11
    clutter-gtk-1.0
    gl

**Comment by rlue** [comment]
Hm, the first line (`pkg_check_modules`) is correct as written — you can see in the build output from above that

```sh
--   Found liblightdm-gobject-1, version 1.18.3
```

It's the second one (under the `PACKAGES` section) that's causing the error. I'm not sure why the vala compiler isn't finding the `liblightdm-gobject-1` package, but I can find at least two other instances of people having the same problem with the upstream pantheon greeter:

* [on GitHub](https://github.com/pimvullers/elementary/issues/149)
* [in AUR](https://aur.archlinux.org/packages/lightdm-pantheon-greeter-git/?comments=all#comment-513271)

  In this case, it looks like the guy solved it by adding the pantheon repository to his `pacman.conf`

Any more ideas?

**Comment by EasyDevCpp** [comment]
-- Checking for modules 'gee-0.8;liblightdm-gobject-1>=**1.2.1**;gdk-x11-3.0;clutter-gtk-1.0;gdk-pixbuf-2.0;gl'
...
--   Found liblightdm-gobject-1, version **1.18.3**

I guess your liblightdm-gobject-1 package might be outdated. Try to find a newer version of it somewhere...

**Comment by EasyDevCpp** [comment]
Yeah got that one wrong... sorry about that.

Enter the following into your terminal:
```ls /usr/share/vala/vapi | grep liblightdm-gobject-1```

What does it print?

Something similar to this?
```
liblightdm-gobject-1.deps
liblightdm-gobject-1.vapi
```

If not than try: (Replace ver with the currently installed vala version)
```ls /usr/share/vala-ver/vapi | grep liblightdm-gobject-1```

If this also refuses to print anything than I guess either the package is broken or buggy.

**Comment by rlue** [comment]
Sorry for the delay in getting back to you. Honestly, I'm not so determined to get this greeter installed anymore, but I'm happy to continue working with you to resolve this issue so we can get it closed up.

```
$ ls /usr/share/vala/vapi/
gee-0.8.vapi  libnm.deps  libnm.vapi
$ sudo fd liblightdm-gobject /
/usr/share/doc/liblightdm-gobject-dev
/usr/share/doc/liblightdm-gobject-1-0
/usr/lib/x86_64-linux-gnu/liblightdm-gobject-1.so.0.0.0
/usr/lib/x86_64-linux-gnu/liblightdm-gobject-1.a
/usr/lib/x86_64-linux-gnu/liblightdm-gobject-1.so
/usr/lib/x86_64-linux-gnu/liblightdm-gobject-1.so.0
/usr/share/lintian/overrides/liblightdm-gobject-1-0
/usr/lib/x86_64-linux-gnu/pkgconfig/liblightdm-gobject-1.pc
/var/lib/dpkg/info/liblightdm-gobject-1-0:amd64.triggers
/var/lib/dpkg/info/liblightdm-gobject-1-0:amd64.symbols
/var/lib/dpkg/info/liblightdm-gobject-dev:amd64.list
/var/lib/dpkg/info/liblightdm-gobject-dev:amd64.md5sums
/var/lib/dpkg/info/liblightdm-gobject-1-0:amd64.md5sums
/var/lib/dpkg/info/liblightdm-gobject-1-0:amd64.shlibs
/var/lib/dpkg/info/liblightdm-gobject-1-0:amd64.list
```

Perhaps this means that `liblightdm-gobject-dev` is not an equivalent package to `liblightdm-gobject-1-dev`? [Here is a link to the package on packages.debian.org](https://packages.debian.org/en/stretch/liblightdm-gobject-dev), but honestly I'm not sure how to determine which files it installs and to where.

**Comment by EasyDevCpp** [comment]
I will send the missing files to you so you just have to copy & paste them... I guess it is the right package but it just forgets to install the vapi files...

**Comment by EasyDevCpp** [comment]
Simply download the archive and follow the added instructions.

[Debian Fix.tar.gz](https://github.com/nick92/Enso-OS/files/2365944/Debian.Fix.tar.gz)

**Comment by rlue** [comment]
:100: that totally fixes it!

After a little more exploring, it turns out that these files are provided by a separate package in Debian, `lightdm-vala`. 

Might I suggest the following changes to the greeter's `README.md`?

```markdown
## Building and Installation

You'll need the following dependencies:

* cmake
* libclutter-gtk-1.0-dev
* libgdk-pixbuf2.0-dev
* libgee-0.8-dev
* libgtk-3-dev
* liblightdm-gobject-dev / liblightdm-gobject-1-dev
* lightdm-vala (Debian only)
* libx11-dev
* valac
```

I'd fork and PR, but honestly I'm too lazy to add another repository to my account for a two-line documentation fix.

**Comment by EasyDevCpp** [comment]
I am glad it's compiling now :+1:
I might send a PR today with the readme extension let's see
