### ISSUE TITLE
Panther Launcher

### ISSUE THREAD

**Issue by Esteban70x7** [nick92/Enso-OS#21]
The Panther Launcher is in the wrong place. The Panther Launcher should be down.
![captura de pantalla de 2018-05-29 15-45-38 indicaciones](https://user-images.githubusercontent.com/39741475/40682753-99a9b532-635a-11e8-85e8-2f25d2795a0c.png)

**Comment by nick92** [comment]
Unfortunately it doesn't follow the position of the panel add-in, but you can get it to sit at the bottom by going into dconf and setting org.rastersoft.panther.show-at-top to false

**Comment by Esteban70x7** [comment]
No problem, I put the Wisker Menu instead of the Panther Launcher.
![captura de pantalla_2018-05-29_19-39-30](https://user-images.githubusercontent.com/39741475/40691081-44d3f5b8-6378-11e8-8a2c-aa1deef158a4.png)
