### ISSUE TITLE
Set desktop background of Thunar doesn't work

### ISSUE THREAD

**Issue by Esteban70x7** [nick92/Enso-OS#22]
Set desktop background of Thunar doesn't work. I did a video with the issue.
https://youtu.be/sibUNtMUmBQ

**Comment by EasyDevCpp** [comment]
Simple solution would be to switch from Thunar to Nemo or Nautilus I guess...

**Comment by nick92** [comment]
We're going to have an issue setting this as thunar throws an error when we aren't running xfdesktop 

> g_shell_quote: assertion 'unquoted_string != NULL' failed

Looking in the [thunar wallpaper plugin code](https://github.com/xfce-mirror/thunar/blob/660d9ceb8509ef82fe3a4a0287014010286bf12c/plugins/thunar-wallpaper/twp-provider.c) the issue is around this area - 

    if (desktop_type != DESKTOP_TYPE_NONE) // this is set to TYPE_NONE so no file_name is set
    {
      file_uri = thunarx_file_info_get_uri (file_info);
      file_name = g_filename_from_uri (file_uri, &hostname, NULL);
      if (hostname != NULL)
        {
          g_free (hostname);
          g_free (file_uri);
          g_free (file_name);

          return;
        }

      g_free (file_uri);
    }
    -----
    // then later on this is returning an empty string error
    escaped_file_name = g_shell_quote (file_name);

**Comment by EasyDevCpp** [comment]
I've just tested Nemo & Nautilus...
Nemo doesn't even has the option
And Nautilus works fine but always creates a new folder named "Wallpapers" with a copy of the wallpaper in it...

I believe that this Thunar-Bug is unfix-able or at least not worth the effort...

**Comment by nick92** [comment]
Going to add this to possible future dev work, but not going to look at it any time soon as isn't that critical
