### ISSUE TITLE
Changing user on greeter should be left - right keys

### ISSUE THREAD

**Issue by nick92** [nick92/Enso-OS#26]
Changing users on the login screen is confusing, clicking doesn't work (or works randomly), left/right arrows don't work. Maybe you should add a small info somewhere on the screen that up/down arrows and the mouse wheel works? Or display users in a vertical column, not a horizontal row, then up/down would make more sense.

**Comment by EasyDevCpp** [comment]
Perhaps vertically goes easier on the eye...
I would rather investigate why things behave like they behave to fix the core of the problem.

**Comment by EasyDevCpp** [comment]
What about applying this to the "Enso-OS/greeter/src/PantheonGreeter.vala" file?
```vala 
case Gdk.Key.Left:
       userlist.select_prev_user ();
       break;
case Gdk.Key.Right:
       userlist.select_next_user ();
       break;
```

**Comment by EasyDevCpp** [comment]
Ok it's not that easy because of the input-field being active by default...
