### ISSUE TITLE
touchpad and keyboard not working

### ISSUE THREAD

**Issue by tresenblanco** [nick92/Enso-OS#29]
enso os 3.0 installed on Toshiba Satellite L45D-B (PSKRGP) 64bits no idea what to do, new user on linux

**Comment by Pommaq** [comment]
Does an external keyboard work?

**Comment by tresenblanco** [comment]
yeah, it works with a USB keyboard/mouse

**Comment by nick92** [comment]
is the touchpad just disabled on start? is there a function + F Key shortcut to enable the touchpad? (usually Function + F4 I think)

**Comment by Pommaq** [comment]
Ok. Can you open the terminal and write "uname -r" then post the results here?

**Comment by nick92** [comment]
Going to close as had no response
