### ISSUE TITLE
Panel icon remains in Plank after settings are closed

### ISSUE THREAD

**Issue by nick92** [nick92/Enso-OS#3]
When panel preferences is selected the panel icon is added to the Plank, this icon then remains there even after the preferences is closed

**Comment by xfranciscox** [comment]
Is there any workaround yet? I'm having this issue on XFCE.

**Comment by nick92** [comment]
Unfortunately I haven't managed to find a solution for this yet, but will post on here if I do

**Comment by nick92** [comment]
This appears to have been fixed on my system, not sure what changed to fix it, unfortunately Plank don't provide that much information on their releases, but FYI I'm running:

> Plank 0.11.2   
> Xfce Panel 4.12.0
