### ISSUE TITLE
Feature Request: Launchpad integration to provide faster patches

### ISSUE THREAD

**Issue by EasyDevCpp** [nick92/Enso-OS#32]
^ title

**Comment by nick92** [comment]
What's the best way of doing this?

**Comment by EasyDevCpp** [comment]
1. We should create a launchpad group similar to this one: https://launchpad.net/elementary
2. Than we have to follow this kind of formular: https://askubuntu.com/questions/71510/how-do-i-create-a-ppa
3. Last we've to add the ppa to the base system: sudo add-apt-repository ppa:our-ppa/ppa

**Comment by nick92** [comment]
ah, I thought you meant some kind of Git integration on Launchpad..

Enso currently has a test and stable PPA's 

[test](https://launchpad.net/~enso-os/+archive/ubuntu/test)
[stable](https://launchpad.net/~enso-os/+archive/ubuntu/stable)

and I have newly created a (team)[https://launchpad.net/~enso-os-team] if you send me your launchpad login details I can add you to it

**Comment by EasyDevCpp** [comment]
Username: easy-dev
E-Mail: easy-dev@web.de

This Issue than could be closed...
