### ISSUE TITLE
Unable to right-click with laptop touchpad.

### ISSUE THREAD

**Issue by Pommaq** [nick92/Enso-OS#35]
As the title says, I have been looking around for settings regarding this but I can't find it. Is it truly missing, bugged or a planned feature?

**Comment by Pommaq** [comment]
Never mind, I'm just dumb. Right-clicking is apparently clicking the pad with three fingers.

**Comment by nick92** [comment]
That's odd, what's your machine specs? is only 2 clicks for me, if you make amendments through the mouse settings app do these apply correctly?

**Comment by Pommaq** [comment]
Never mind again. It is clicking with two fingers...
That being said, making the touchpad left-handed in mouse settings does apply. 
But then clicking with one finger counts as right click and using two counts as left which I feel is odd considering the settings.
Perhaps call it "Inverted mode disabled/enabled"?
