### ISSUE TITLE
changing th clock format

### ISSUE THREAD

**Issue by charlie45000** [nick92/Enso-OS#41]
Hello,
I can't change the date format (from 12 to 24 hour?) I tried to put "time_format = HH mm" in the greeter.conf, but it did not work is there any way to change it?

tank you for your help!

**Comment by nick92** [comment]
This is currently hard coded so can't be changed - will add the request to the project roadmap for future development to allow setting in the config 

Thanks for raising

**Comment by charlie45000** [comment]
thank you for your answer!!
for the moment, how could I hard change the format?

**Comment by nick92** [comment]
In the greeter/src/Widgets/TimeLabel.vala file you'll have to change the below code:

``` vala
 // Time display, see http://valadoc.org/#!api=glib-2.0/GLib.DateTime.format for more details
 var time_format = _("%l:%M");
```

Look at the datetime article to see what values to change to

**Comment by charlie45000** [comment]
It worked !!

Again thank you for your help!

**Comment by nick92** [comment]
this has been released so will close this ticket
