### ISSUE TITLE
Better integration theme enso os

### ISSUE THREAD

**Issue by Esteban70x7** [nick92/Enso-OS#43]
One suggestion, change theme to improve integration.
![better integration1](https://user-images.githubusercontent.com/39741475/52171301-5c7fa880-2739-11e9-8906-91a7f3e6a432.png)
![better integration2](https://user-images.githubusercontent.com/39741475/52171302-5c7fa880-2739-11e9-95b0-287a42e6439a.png)

**Comment by nick92** [comment]
This is due to Enso not supporting dark themes - will add to future roadmap to add dark theme support

**Comment by ShadowFighter99** [comment]
Add a dynamic theme , (light and dark), like zorin os

**Comment by nick92** [comment]
the Enso theme already contains both light and dark elements and styling, the icons just need updating for the dark theme from the defaults

**Comment by paullinuxthemer** [comment]
I can help you with the theming-part.  As Paulxfce (see gnome-look.org) I have some years of theme-modding in my head.  As you said: the assets-file does not contain all the title-buttons.  I can, if you want,  create a modified assets-svg  to address this issue.

**Comment by ShadowFighter99** [comment]
It'd be good to use crontab or smthing like that to apply dynic themes, colors, backgrounds , i can help ,  but it would be great to make a UI of that

**Comment by nick92** [comment]
If you guys are happy to fix these issues then go ahead, the theme is a form of [Arc](https://github.com/arc-design/arc-theme) with the main change just being the header icons, any help is appreciated as I don't have any time to work on this atm

**Comment by paullinuxthemer** [comment]
I'm not that familiar with this github push and such.  I will create a proper assets.svg, from which the assets are made.  And then create a new assets-folder in  GTK3, with support for dark theme.  I'll see then, how I will send it to you for review.

**Comment by paullinuxthemer** [comment]
And while were are at it, I can build a dark theme for you as well If you are interested...

**Comment by nick92** [comment]
Ye that would be great, just upload it to a new repo if that's easier but we can work that out later

**Comment by paullinuxthemer** [comment]
Great, I'll work on it in the following days.  
Btw, I really like this simple , but beautiful distro.  Happy to contribute.

**Comment by paullinuxthemer** [comment]
@nick92 
I've completed the theme with all the necessary graphics, with support for applications that require dark theme. Also added support for GTK 2.0.  You can find it [here](https://github.com/paullinuxthemer/Enso-theme)
Please let me know if you want any other help in this...

**Comment by paullinuxthemer** [comment]
Workin on a dark version.  But need help.  Where does the launcher get its code for the background.  It stays white, although it should be dark.
Also using a dark theme requires a Paper-icon-theme with support for dark theme.
And AppHive stays white.

Screenshot:
![screenshot-dark](https://user-images.githubusercontent.com/26058111/66713968-ded46800-edb0-11e9-874a-2a096ef3fd1e.jpg)

**Comment by nick92** [comment]
Both look great, thanks for doing that it's much appreciated, launchy and apphive have custom styles that's take from the css stored against both projects, if you just leave them for now I'll look at getting the dark theme sorted for both and then add it to the new theme

**Comment by paullinuxthemer** [comment]
If you have a preference,  than I can develop it further.

**Comment by nick92** [comment]
Don't have a preference with the launcher, if you want to develop it just to fit in with everything then that would be fine, I'm working on apphive at the minute and am going to re-style it so leave that for now

**Comment by paullinuxthemer** [comment]
No,  I Mean, I've made several variants of the theme.   Which one you like me to develop further?

**Comment by nick92** [comment]
If you could do variant 3 with the slight transparency but without divider lines being visible in the menu that would be great

and yes Enso 0.4 will be using version 4.14

**Comment by paullinuxthemer** [comment]
@nick92 
The final versions of both light and dark Enso-theme are now in the [repository](https://github.com/paullinuxthemer/Enso-theme)
The Dark theme requires a modified dark launcher and Apphive, and also an icon-theme that supports dark themes.  

There are some issues however:

Switching from Light to dark theme requires a log-out-log-in operation, because GTK2 does not switch properly. Some dark elements remain dark even after switching to the light-version.  

In fact, a smooth switch can only be done if you move to XFCE 4.14, because then, everything is GTK3.  

I've not yet got into developing a version for XFCE 4.14.  (It requires some adjustments for the new Thunar).
