### ISSUE TITLE
How to install this on budgie/gnome?

### ISSUE THREAD

**Issue by ghost** [nick92/Enso-OS#5]
Where do I need to put which folders to install this theme?

**Comment by nick92** [comment]
As far as I'm aware just copy it into /usr/share/themes and then change the selected theme to Enso

**Comment by skullscream** [comment]
Problem is I don't know which folders from here? https://github.com/nick92/Enso-OS/tree/master/theme

**Comment by nick92** [comment]
Everything really, if you want to save space you could drop xfwm4, cinnamon, unity and metacity - but the rest you will probably need, mainly the GTK folders really.
