### ISSUE TITLE
Wallpaper change not always applying

### ISSUE THREAD

**Issue by nick92** [nick92/Enso-OS#52]
Wallpaper change not always applying in Gala, logging off and back on again or resizing the window in virtual instance solves the issue

**Comment by nreith** [comment]
I second this one.

Great distro btw! I love the look, and the solid XFCE and Xubuntu 18.04 upstream.
I'd be happy to help if you're open to an open-source lurker but newbie contributor.

**Comment by nick92** [comment]
This issue is now resolved in the 0.4 release
