### ISSUE TITLE
Touchpad

### ISSUE THREAD

**Issue by mdfuerst** [nick92/Enso-OS#56]
Just started giving Enso OS a try and I'm really enjoying the combination of the lightweight XFCE environment along with the more pleasant visuals of Gala. The one thing that I'm having trouble with is getting all the functions of my touchpad to work. I'm using a Thinkpad X300, and on other distros I've had both the edge scrolling and tap-to-click work out of the box. I can get the edge scrolling working, although each time I restart I have to reenable it in the settings. I've clicked the checkbox. The "tap touchpad to click" box in the Mouse and Touchpad settings, but to no effect. I've done a little bit of sleuthing via Google, and tried to install synaptic, although that seemed to disable my keyboard. Any ideas you might have would be much appreciated, as I'd love to get things all set up and continue using Enso as my daily distro.

**Comment by nick92** [comment]
I have been told that running gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true in the terminal should resolve the tap to click issue

**Comment by mdfuerst** [comment]
That seems to have done the trick, thanks! 

Would a similar gsettings command from the terminal help to keep the edge scrolling active after restart? A quick google search shows that people have used gsettings set org.gnome.desktop.peripherals.touchpad scroll-method 'edge-scrolling', although it doesn't seem to work to activate edge scrolling for me, or keep it active after restart. Thanks again for the help.

**Comment by Suleman-Elahi** [comment]
> I have been told that running gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true in the terminal should resolve the tap to click issue

Thanks for this...for me touchpad was working on login screen and during installation but on desktop, it wasn't functioning. You won't believe, I spent last 1-1/2 hours looking for the solution. Btw is the default Enso theme available in dark version?
