### ISSUE TITLE
Notification settings apply, but have no effect

### ISSUE THREAD

**Issue by Pommaq** [nick92/Enso-OS#61]
As mentioned. Modifying the settings for notification popups shows no visible changes, but running 
`xfconf-query -vc xfce4-notifyd -m`
 and then changing settings shows that they are indeed applied. 
I have opened a similar issue some time ago, #30. 
I'm currently investigating what causes this issue.

**Comment by Pommaq** [comment]
Alright, so the settings are overridden by Gala, which is for now an intended feature. As such I'll be looking for a way to remove the notifications setting from the settings menu.
One method is to append `Hidden=true` to /usr/share/applications/xfce4-notifyd-config.desktop.
Ofcourse, a cleaner method would be to simply remove it altogether, but I'm not sure if that removes the notifyd daemon aswell

**Comment by Pommaq** [comment]
Tried removing xfce4-notifyd and rebooting on a virtual machine. The notifications appear to still function as they usually do. So removing xfce4-notifyd is a viable (and possibly cleaner) option

**Comment by nick92** [comment]
Great, thanks for investigating that - will add this to the next release

**Comment by melomane63** [comment]
to solve bug it is not necessary to remove xfce4-notifyd 

only do this:
sudo mousepad /usr/share/dbus-1/services/org.xfce.xfce4-notifyd.Notifications.service

paste this:

[D-BUS Service]
Name=org.freedesktop.Notifications
Exec=/usr/lib/x86_64-linux-gnu/xfce4/notifyd/xfce4-notifyd
SystemdService=xfce4-notifyd.service

Reboot

OR

remove AND reinstall xfce4-notifyd,  reboot

 solve also this bug:
https://github.com/nick92/Enso-OS/issues/38

**Comment by nick92** [comment]
this is closed now as the settings has been removed from version 0.4
