### ISSUE TITLE
App Hive is seriously lagged

### ISSUE THREAD

**Issue by MatiasBoldrini** [nick92/Enso-OS#66]
Everytime i open app hive , it is very lagged , specially in the search bar.

**Comment by lazydevyo** [comment]
Yeah app hive is super laggy sometimes when you install something it totally freezes till its done

**Comment by nick92** [comment]
I'm working on a new version of Apphive currently which will resolve some of the lagging issues

**Comment by nick92** [comment]
The performance in the latest version of apphive resolves these issues
