### ISSUE TITLE
Installer is bugged

### ISSUE THREAD

**Issue by MatiasBoldrini** [nick92/Enso-OS#67]
When i start the live iso , appears a window saying "Try Enso" or "install Enso" ,  the problem is that this screen is too big and only see the "Try Enso" Button. This happen in both of my hp laptops

**Comment by nick92** [comment]
What size / resolution is your laptop screen?

**Comment by ShadowFighter99** [comment]
1366x768 .
How can i customize Gala?? , The "dconf-editor" doesnt work , and the system settings neirher.

**Comment by nick92** [comment]
What part of Gala are you looking to customize?

**Comment by ShadowFighter99** [comment]
I use. A WindowHeaderplugin , and , when i maximize. Awindow , the window frame doesnt disappear 
![IMG_20190906_081302063](https://user-images.githubusercontent.com/50892896/64423986-4266c980-d07e-11e9-8c84-5d1b870b4321.jpg)

**Comment by nick92** [comment]
This issue should be resolved in version 0.4
