### ISSUE TITLE
XFCE 4.14 When?

### ISSUE THREAD

**Issue by Fatih20** [nick92/Enso-OS#68]
I think the implementation of XFCE 4.14 will solve amny issues and further make it easier for enso to be more modern.

**Comment by axelmaker** [comment]
Xubuntu 20.04 released. Are you already working on a new version?

**Comment by nick92** [comment]
Yup, aiming to release Enso 0.4 by June this year

**Comment by nick92** [comment]
0.4 has now been released that includes this version of XFCE
