### ISSUE TITLE
Please put this on the AUR!

### ISSUE THREAD

**Issue by djsavvy** [nick92/Enso-OS#7]
It's a pretty awesome theme, and I'd love to see it on the AUR. I'd be more than willing to write a PKGBUILD for it too.

**Comment by addy-dclxvi** [comment]
Agree! I want to see this on AUR as well

**Comment by djsavvy** [comment]
https://aur.archlinux.org/packages/lightdm-enso-os-greeter-git/

**Comment by nick92** [comment]
Perfect, thanks a lot for doing that
