### ISSUE TITLE
Doc page link in installer doesn't work

### ISSUE THREAD

**Issue by nick92** [nick92/Enso-OS#71]
I wanted to fix a broken link in the Ubiquity installer slide, but I don't see the source files on your GitHub, I'm talking about the "Docs page" link

**Comment by TanZng** [comment]
Old link: http://enso-os.site/learn.html
New link: http://docs.enso-os.site/learn/

![img](https://user-images.githubusercontent.com/25267490/82765557-7e44e900-9ddd-11ea-9122-3dab30db23a2.jpg)

**Comment by nick92** [comment]
This has been resolved in version 0.4
