### ISSUE TITLE
Enso OS desktop with Arch Linux?

### ISSUE THREAD

**Issue by JimScope** [nick92/Enso-OS#75]
It is posible to use the desktop of Enso with arch linux using xfwm instead of gala?
What would be their dependencies?

**Comment by nick92** [comment]
You can install all the packages separately, the theme can be found [here] (https://github.com/enso-os/theme) and the launcher can be installed from [source ](https://github.com/nick92/launchy)

what else are you looking to use from Enso?

**Comment by Senyaaa** [comment]
> You can install all the packages separately, the theme can be found [here] (https://github.com/enso-os/theme) and the launcher can be installed from [source ](https://github.com/nick92/launchy)
> 
> what else are you looking to use from Enso?

I can't post an issue in [launchy repository](https://github.com/nick92/launchy), but it doesn't compile for me. Xubuntu 19.10, shows an error when I'm trying to run it after compiling: (launchy:5917): GLib-GIO-ERROR **: 14:11:54.136: Settings schema 'org.enso.launchy' is not installed
Trace/breakpoint trap (core dumped)

**Comment by nick92** [comment]
you just need to run an install to install the schema for it: so just run sudo ninja install and then try again

**Comment by Suleman-Elahi** [comment]
@JimScope were you able to made it for Arch ?
