### ISSUE TITLE
Congratulations on the Enso OS

### ISSUE THREAD

**Issue by lynxmedeiros** [nick92/Enso-OS#8]
Hello team,
Congratulations on the _Enso OS_ project, a very beautiful and easy system to use for anyone, even for the user who is starting to use Linux. _Enso OS_ has a perfect combination of icons and desktop environment.
And congratulations to the site, which has a great explanation to insinuate how to install _Enso OS_ and also how to make booting from flash drive.
Greetings.

**Comment by lynxmedeiros** [comment]
I am testing in the Virtual Box, the system starts with 440 Mb of memory, and is performing well.

**Comment by nick92** [comment]
Thank you for your very nice feedback, glad to hear our OS is working well for you
