### ISSUE TITLE
Layot switch dont work

### ISSUE THREAD

**Issue by msibirov** [nick92/Enso-OS#83]
the switch just doesn't work, I've tried many different ways already, but it doesn't work. Help

**Comment by nick92** [comment]
is this the layout switch in the panel?

**Comment by Xyr0s1gn** [comment]
> the switch just doesn't work, I've tried many different ways already, but it doesn't work. Help

is the symptoms like here #55 ?

**Comment by nick92** [comment]
Yes this is a duplicate issue so I will close this one
