### ISSUE TITLE
Issue compiling greeter.

### ISSUE THREAD

**Issue by Isaac-bankier** [nick92/Enso-OS#9]
Hi nick. I was trying to setup the greeter on archlinux so I downloaded it from the AUR but found there was an issue building it. I think that the issue is that the make file is not up to date with the new changes made a few days ago. Here is the raw output from yaourt 

`[isaac@cs30 ~]$ yaourt -S lightdm-enso-os-greeter-git

==> Downloading lightdm-enso-os-greeter-git PKGBUILD from AUR...
x .SRCINFO
x PKGBUILD
Kozmik commented on 2017-10-03 12:52			 
Building fails for me with this:

== Retrieving sources...
- Updating lightdm-enso-os-greeter-git svn repo...
Skipped '.'
svn: E155007: None of the targets are working copies
== WARNING: Failure while updating lightdm-enso-os-greeter-git svn repo
== Validating source files with md5sums...
lightdm-enso-os-greeter-git ... Skipped
== Extracting sources...
- Creating working copy of greeter svn repo...
== Starting pkgver()...
== ERROR: pkgver is not allowed to contain colons, hyphens or whitespace.
== ERROR: pkgver() generated an invalid version: Unversioned directory

areuz commented on 2017-10-05 23:48			 
A lot of warnings about unhandled errors and deprecated statements, but otherwise works fine for me.

lightdm-enso-os-greeter-git 16-1  (2017-09-09 16:11)
( Unsupported package: Potentially dangerous ! )
==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
==> y

Please add $VISUAL to your environment variables
for example:
export VISUAL="vim" (in ~/.bashrc)
(replace vim with your favorite editor)

==> Edit PKGBUILD with:  vim

==> lightdm-enso-os-greeter-git dependencies:
 - cairo (already installed)
 - clutter (already installed)
 - clutter-gtk (already installed)
 - gdk-pixbuf2 (already installed)
 - glib2 (already installed)
 - glibc (already installed)
 - gtk3 (already installed)
 - libgee (already installed)
 - libgl (already installed)
 - libx11 (already installed)
 - lightdm (already installed)
 - vala (already installed)
 - cmake (already installed) [makedepend]
 - svn (already installed) [makedepend]
 - git (already installed) [makedepend]

==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
==> n

==> Continue building lightdm-enso-os-greeter-git ? [Y/n]
==> -----------------------------------------------------
==> y

==> Building and installing package
==> Making package: lightdm-enso-os-greeter-git 16-1 (Mon Oct 16 19:09:41 AEDT 2017)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning lightdm-enso-os-greeter-git svn repo...
A    lightdm-enso-os-greeter-git/AUTHORS
A    lightdm-enso-os-greeter-git/CMakeLists.txt
A    lightdm-enso-os-greeter-git/CODE_OF_CONDUCT.md
A    lightdm-enso-os-greeter-git/LICENSE
A    lightdm-enso-os-greeter-git/README.md
A    lightdm-enso-os-greeter-git/cmake
A    lightdm-enso-os-greeter-git/cmake/FindVala.cmake
A    lightdm-enso-os-greeter-git/cmake/GResource.cmake
A    lightdm-enso-os-greeter-git/cmake/GSettings.cmake
A    lightdm-enso-os-greeter-git/cmake/Makefile
A    lightdm-enso-os-greeter-git/cmake/ParseArguments.cmake
A    lightdm-enso-os-greeter-git/cmake/README
A    lightdm-enso-os-greeter-git/cmake/README.Vala.rst
A    lightdm-enso-os-greeter-git/cmake/Tests.cmake
A    lightdm-enso-os-greeter-git/cmake/Translations.cmake
A    lightdm-enso-os-greeter-git/cmake/ValaPrecompile.cmake
A    lightdm-enso-os-greeter-git/cmake/ValaVersion.cmake
A    lightdm-enso-os-greeter-git/data
A    lightdm-enso-os-greeter-git/data/.face
A    lightdm-enso-os-greeter-git/data/Greeter.css
A    lightdm-enso-os-greeter-git/data/avatar-default.svg
A    lightdm-enso-os-greeter-git/data/css.gresource.xml
A    lightdm-enso-os-greeter-git/data/fingerprint.svg
A    lightdm-enso-os-greeter-git/data/pantheon-greeter.conf
A    lightdm-enso-os-greeter-git/data/pantheon-greeter.desktop
A    lightdm-enso-os-greeter-git/data/power-button.png
A    lightdm-enso-os-greeter-git/data/power.svg
A    lightdm-enso-os-greeter-git/data/shader-old.glsl
A    lightdm-enso-os-greeter-git/debian
A    lightdm-enso-os-greeter-git/debian/README
A    lightdm-enso-os-greeter-git/debian/changelog
A    lightdm-enso-os-greeter-git/debian/compat
A    lightdm-enso-os-greeter-git/debian/control
A    lightdm-enso-os-greeter-git/debian/copyright
A    lightdm-enso-os-greeter-git/debian/rules
A    lightdm-enso-os-greeter-git/debian/source
A    lightdm-enso-os-greeter-git/debian/source/format
A    lightdm-enso-os-greeter-git/po
A    lightdm-enso-os-greeter-git/po/CMakeLists.txt
A    lightdm-enso-os-greeter-git/po/ace.po
A    lightdm-enso-os-greeter-git/po/af.po
A    lightdm-enso-os-greeter-git/po/ak.po
A    lightdm-enso-os-greeter-git/po/am.po
A    lightdm-enso-os-greeter-git/po/an.po
A    lightdm-enso-os-greeter-git/po/ar.po
A    lightdm-enso-os-greeter-git/po/ast.po
A    lightdm-enso-os-greeter-git/po/az.po
A    lightdm-enso-os-greeter-git/po/be.po
A    lightdm-enso-os-greeter-git/po/bg.po
A    lightdm-enso-os-greeter-git/po/bn.po
A    lightdm-enso-os-greeter-git/po/bs.po
A    lightdm-enso-os-greeter-git/po/ca.po
A    lightdm-enso-os-greeter-git/po/ckb.po
A    lightdm-enso-os-greeter-git/po/cs.po
A    lightdm-enso-os-greeter-git/po/da.po
A    lightdm-enso-os-greeter-git/po/de.po
A    lightdm-enso-os-greeter-git/po/el.po
A    lightdm-enso-os-greeter-git/po/en_AU.po
A    lightdm-enso-os-greeter-git/po/en_CA.po
A    lightdm-enso-os-greeter-git/po/en_GB.po
A    lightdm-enso-os-greeter-git/po/eo.po
A    lightdm-enso-os-greeter-git/po/es.po
A    lightdm-enso-os-greeter-git/po/et.po
A    lightdm-enso-os-greeter-git/po/eu.po
A    lightdm-enso-os-greeter-git/po/fa.po
A    lightdm-enso-os-greeter-git/po/fi.po
A    lightdm-enso-os-greeter-git/po/fil.po
A    lightdm-enso-os-greeter-git/po/fr.po
A    lightdm-enso-os-greeter-git/po/fr_CA.po
A    lightdm-enso-os-greeter-git/po/ga.po
A    lightdm-enso-os-greeter-git/po/gl.po
A    lightdm-enso-os-greeter-git/po/gu.po
A    lightdm-enso-os-greeter-git/po/he.po
A    lightdm-enso-os-greeter-git/po/hi.po
A    lightdm-enso-os-greeter-git/po/hr.po
A    lightdm-enso-os-greeter-git/po/hu.po
A    lightdm-enso-os-greeter-git/po/hy.po
A    lightdm-enso-os-greeter-git/po/ia.po
A    lightdm-enso-os-greeter-git/po/id.po
A    lightdm-enso-os-greeter-git/po/it.po
A    lightdm-enso-os-greeter-git/po/ja.po
A    lightdm-enso-os-greeter-git/po/ka.po
A    lightdm-enso-os-greeter-git/po/ko.po
A    lightdm-enso-os-greeter-git/po/ku.po
A    lightdm-enso-os-greeter-git/po/ky.po
A    lightdm-enso-os-greeter-git/po/lb.po
A    lightdm-enso-os-greeter-git/po/lo.po
A    lightdm-enso-os-greeter-git/po/lt.po
A    lightdm-enso-os-greeter-git/po/lv.po
A    lightdm-enso-os-greeter-git/po/ml.po
A    lightdm-enso-os-greeter-git/po/mn.po
A    lightdm-enso-os-greeter-git/po/mr.po
A    lightdm-enso-os-greeter-git/po/ms.po
A    lightdm-enso-os-greeter-git/po/my.po
A    lightdm-enso-os-greeter-git/po/nb.po
A    lightdm-enso-os-greeter-git/po/nl.po
A    lightdm-enso-os-greeter-git/po/nn.po
A    lightdm-enso-os-greeter-git/po/pantheon-greeter.pot
A    lightdm-enso-os-greeter-git/po/pl.po
A    lightdm-enso-os-greeter-git/po/pt.po
A    lightdm-enso-os-greeter-git/po/pt_BR.po
A    lightdm-enso-os-greeter-git/po/ro.po
A    lightdm-enso-os-greeter-git/po/ru.po
A    lightdm-enso-os-greeter-git/po/rue.po
A    lightdm-enso-os-greeter-git/po/si.po
A    lightdm-enso-os-greeter-git/po/sk.po
A    lightdm-enso-os-greeter-git/po/sl.po
A    lightdm-enso-os-greeter-git/po/sma.po
A    lightdm-enso-os-greeter-git/po/sq.po
A    lightdm-enso-os-greeter-git/po/sr.po
A    lightdm-enso-os-greeter-git/po/sr@latin.po
A    lightdm-enso-os-greeter-git/po/sv.po
A    lightdm-enso-os-greeter-git/po/sw.po
A    lightdm-enso-os-greeter-git/po/ta.po
A    lightdm-enso-os-greeter-git/po/te.po
A    lightdm-enso-os-greeter-git/po/th.po
A    lightdm-enso-os-greeter-git/po/tl.po
A    lightdm-enso-os-greeter-git/po/tr.po
A    lightdm-enso-os-greeter-git/po/ug.po
A    lightdm-enso-os-greeter-git/po/uk.po
A    lightdm-enso-os-greeter-git/po/ur.po
A    lightdm-enso-os-greeter-git/po/vi.po
A    lightdm-enso-os-greeter-git/po/zh_CN.po
A    lightdm-enso-os-greeter-git/po/zh_HK.po
A    lightdm-enso-os-greeter-git/po/zh_TW.po
A    lightdm-enso-os-greeter-git/src
A    lightdm-enso-os-greeter-git/src/Gateways
A    lightdm-enso-os-greeter-git/src/Gateways/DummyGateway.vala
A    lightdm-enso-os-greeter-git/src/Gateways/LightDMGateway.vala
A    lightdm-enso-os-greeter-git/src/Gateways/LoginGateway.vala
A    lightdm-enso-os-greeter-git/src/Interfaces
A    lightdm-enso-os-greeter-git/src/Interfaces/Credentials.vala
A    lightdm-enso-os-greeter-git/src/Interfaces/LoginMask.vala
A    lightdm-enso-os-greeter-git/src/LoginOptions
A    lightdm-enso-os-greeter-git/src/LoginOptions/GuestLogin.vala
A    lightdm-enso-os-greeter-git/src/LoginOptions/LoginOption.vala
A    lightdm-enso-os-greeter-git/src/LoginOptions/ManualLogin.vala
A    lightdm-enso-os-greeter-git/src/LoginOptions/UserLogin.vala
A    lightdm-enso-os-greeter-git/src/PantheonGreeter.vala
A    lightdm-enso-os-greeter-git/src/SettingsDaemon.vala
A    lightdm-enso-os-greeter-git/src/UserList.vala
A    lightdm-enso-os-greeter-git/src/UserListActor.vala
A    lightdm-enso-os-greeter-git/src/Widgets
A    lightdm-enso-os-greeter-git/src/Widgets/CredentialsArea.vala
A    lightdm-enso-os-greeter-git/src/Widgets/FingerprintCredentials.vala
A    lightdm-enso-os-greeter-git/src/Widgets/LoginBox.vala
A    lightdm-enso-os-greeter-git/src/Widgets/LoginButtonCredentials.vala
A    lightdm-enso-os-greeter-git/src/Widgets/PasswordCredentials.vala
A    lightdm-enso-os-greeter-git/src/Widgets/PowerLabel.vala
A    lightdm-enso-os-greeter-git/src/Widgets/TimeLabel.vala
A    lightdm-enso-os-greeter-git/src/Widgets/Wallpaper.vala
A    lightdm-enso-os-greeter-git/src/config.vala.cmake
A    lightdm-enso-os-greeter-git/vapi
A    lightdm-enso-os-greeter-git/vapi/gl.vapi
Checked out revision 26.
==> Validating source files with md5sums...
    lightdm-enso-os-greeter-git ... Skipped
==> Extracting sources...
  -> Creating working copy of greeter svn repo...
==> Starting pkgver()...
==> Updated version: lightdm-enso-os-greeter-git 26-1
==> Starting build()...
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for modules 'gee-0.8;liblightdm-gobject-1>=1.2.1;gdk-x11-3.0;clutter-gtk-1.0;gdk-pixbuf-2.0;gl'
--   Found gee-0.8, version 0.20.0
--   Found liblightdm-gobject-1, version 1.22.0
--   Found gdk-x11-3.0, version 3.22.24
--   Found clutter-gtk-1.0, version 1.8.4
--   Found gdk-pixbuf-2.0, version 2.36.10
--   Found gl, version 17.2.2
-- Found Vala: /usr/bin/valac  
-- checking for a minimum Vala version of 0.26.0
--   found Vala, version 0.38.2
-- GSettings schemas will be installed locally.
-- GSettings shemas will be compiled.
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/yaourt-tmp-isaac/aur-lightdm-enso-os-greeter-git/src/lightdm-enso-os-greeter-git/build
make[2]: *** No rule to make target '../data/shader.glsl', needed by 'data/css.gresource.c'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:99: CMakeFiles/pantheon-greeter.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build lightdm-enso-os-greeter-git.
==> Restart building lightdm-enso-os-greeter-git ? [y/N]
==> ----------------------------------------------------
==> 
`

The last few lines make me think that this is just a simple problem with the make file.

**Comment by nick92** [comment]
My bad, committed a change to the wrong branch. Will fix this tonight

**Comment by Isaac-bankier** [comment]
Thanks!

**Comment by nick92** [comment]
Should be fixed now
